---
title: "Predictive Policing"
output:
  html_document:
    df_print: paged
---
























# Police feedback loops -- step by step function



```{r}
# true crime
a <- 0.5
b <- 0.5

# police beliefs about crime
ac <- 0.2
bc <- 0.8

# police crime detection when visiting an area
x <- 0.1
```



```{r}
crime1 <- function(ac, bc, a, b, x) {

  outcome <- c(1, 0)
  ac <- ac/(ac+bc)
  bc <- bc/(ac+bc)
  a <- a/(a+b)
  b <- b/(a+b)
    
  flip <- sample(outcome, 1, prob=c(ac,bc))
    
    if(flip==1) {
      learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
      return(c(ac, bc, learn_a))
    }
    else        {
      learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
      return(c(ac, bc, learn_b))
    
    }
}

crime2 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime1(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime3 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime2(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime4 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime3(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime5 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime4(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime6 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime5(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime7 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime6(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime8 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime7(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime9 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime8(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime10 <- function(ac, bc, a, b, x) {
  
  outcome <- c(1, 0)
  a <- a/(a+b)
  b <- b/(a+b)
  before <- crime9(ac, bc, a, b, x)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}
```

# Examples of outputs

```{r}
crime1(0.2, 0.8, 0.5, 0.5, 0.2)
crime2(0.2, 0.8, 0.5, 0.5, 0.2)
crime2(0.2, 0.8, 0.5, 0.5, 0.2)
crime3(0.2, 0.8, 0.5, 0.5, 0.2)
crime4(0.2, 0.8, 0.5, 0.5, 0.2)
crime5(0.2, 0.8, 0.5, 0.5, 0.2)
crime6(0.2, 0.8, 0.5, 0.5, 0.2)
crime7(0.2, 0.8, 0.5, 0.5, 0.2)
crime8(0.2, 0.8, 0.5, 0.5, 0.2)
crime9(0.2, 0.8, 0.5, 0.5, 0.2)
crime10(0.2, 0.8, 0.5, 0.5, 0.2)
```

# Do we learn anything?

```{r}
library(ggplot2)
library(gridExtra) 
library(ggpubr)
```

```{r}
# crime10(0.2, 0.8, 0.5, 0.5, 0.2)
r10a <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.2), 2)[1]) 
r10b <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.2), 2)[2]) 
r10aa <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.6), 2)[1]) 
r10bb <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.6), 2)[2])
r10aaa <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.9), 2)[1]) 
r10bbb <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.9), 2)[2])
```

```{r}
data <- as.data.frame(r10a)
a <- ggplot(data, aes(x=r10a)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="grey") + 
  theme_bw() +
  geom_vline(xintercept = 0.2, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas A")

data <- as.data.frame(r10b)
b <- ggplot(data, aes(x=r10b)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="white") + 
  theme_bw() +
  geom_vline(xintercept = 0.8, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas B")

data <- as.data.frame(r10aa)
aa <- ggplot(data, aes(x=r10aa)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="grey") + 
  theme_bw() +
  geom_vline(xintercept = 0.2, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas A")

data <- as.data.frame(r10bb)
bb <- ggplot(data, aes(x=r10bb)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="white") + 
  theme_bw() +
  geom_vline(xintercept = 0.8, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas B")

data <- as.data.frame(r10aaa)
aaa <- ggplot(data, aes(x=r10aaa)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="grey") + 
  theme_bw() +
  geom_vline(xintercept = 0.2, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas A")

data <- as.data.frame(r10bbb)
bbb <- ggplot(data, aes(x=r10bbb)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="white") + 
  theme_bw() +
  geom_vline(xintercept = 0.8, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas B")
```

```{r}
plot1 <- ggarrange(a, b, nrow=1, ncol=2)
plot1
plot2 <- ggarrange(aa, bb, nrow=1, ncol=2)
plot2
plot3 <- ggarrange(aaa, bbb, nrow=1, ncol=2)
plot3
```

# Police acting on reports


```{r}
crime1 <- function(ac, bc, a, b, x, r) {

  outcome <- c(1, 0)
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  a <- a/(a+b)
  b <- b/(a+b)
    
  flip <- sample(outcome, 1, prob=c(ac,bc))
  # initial police decision depends on rate of crime reporting x
    
    if(flip==1) {
      learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
      return(c(ac, bc, learn_a))
    }
    else        {
      learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
      return(c(ac, bc, learn_b))
    
    }
}

crime2 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime1(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime3 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime2(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime4 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime3(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime5 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime4(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime6 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime5(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime7 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime6(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime8 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime7(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime9 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime8(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}

crime10 <- function(ac, bc, a, b, x, r) {
  
  outcome <- c(1, 0)
  before <- crime9(ac, bc, a, b, x, r)
  ac <- tail(before, 2)[1]
  bc <- tail(before, 2)[2]
  ac <- (1/2*(ac)+1/2*(a*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  bc <- (1/2*(bc)+1/2*(b*r))/((1/2*(ac)+1/2*(a*r))+(1/2*(bc)+1/2*(b*r)))
  
  flip <- sample(outcome, 1, prob=c(ac,bc))
  
  if(flip==1) {
    learn_a <- c((ac+a*x)/(ac+a*x+bc), bc/(ac+a*x+bc))
    return(c(before, learn_a))
  }
  else        {
    learn_b <- c(ac/(ac+b*x+bc), (bc+b*x)/(ac+b*x+bc))
    return(c(before, learn_b))
    
  }
}
```

```{r}
# crime10(0.2, 0.8, 0.5, 0.5, 0.2)
r10a <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.2, 0.2), 2)[1]) 
r10b <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.2, 0.2), 2)[2]) 
r10aa <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.6, 0.6), 2)[1]) 
r10bb <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.6, 0.6), 2)[2])
r10aaa <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.9, 0.9), 2)[1]) 
r10bbb <- replicate(1000, tail(crime10(0.2, 0.8, 0.5, 0.5, 0.9, 0.9), 2)[2])
```

```{r}
data <- as.data.frame(r10a)
a <- ggplot(data, aes(x=r10a)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="grey") + 
  theme_bw() +
  geom_vline(xintercept = 0.2, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas A")

data <- as.data.frame(r10b)
b <- ggplot(data, aes(x=r10b)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="white") + 
  theme_bw() +
  geom_vline(xintercept = 0.8, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas B")

data <- as.data.frame(r10aa)
aa <- ggplot(data, aes(x=r10aa)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="grey") + 
  theme_bw() +
  geom_vline(xintercept = 0.2, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas A")

data <- as.data.frame(r10bb)
bb <- ggplot(data, aes(x=r10bb)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="white") + 
  theme_bw() +
  geom_vline(xintercept = 0.8, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas B")

data <- as.data.frame(r10aaa)
aaa <- ggplot(data, aes(x=r10aaa)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="grey") + 
  theme_bw() +
  geom_vline(xintercept = 0.2, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas A")

data <- as.data.frame(r10bbb)
bbb <- ggplot(data, aes(x=r10bbb)) + 
  geom_histogram(binwidth = 0.05, color="black", fill="white") + 
  theme_bw() +
  geom_vline(xintercept = 0.8, linetype="dotted", color = "black", size=0.5) +
  geom_vline(xintercept = 0.5, linetype="dashed", color = "red", size=0.5) +
  xlab("believed crime rates in areas B")
```



```{r}
plot1 <- ggarrange(a, b, nrow=1, ncol=2)
plot1
plot2 <- ggarrange(aa, bb, nrow=1, ncol=2)
plot2
plot3 <- ggarrange(aaa, bbb, nrow=1, ncol=2)
plot3
```